services:
  angular-app:
    build:
      context: .
      dockerfile: muteni-bank/Dockerfile
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"
    restart: always
